apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openvpn
  namespace: media
spec:
  encryptedData:
    password: AgBAVFK6PjpSi1VK5OVGAvG6KKXFT4BMXNwvWawHS35ZM3znKX5hbChwOXNC0BeEpxBG1C3VxfI2/YyeIXybaoDW92pwrcTvu7oTt86XQ19Gp+K6YYn7FrPVocp5BEbbclNGLQrh23LIqRf/knrV9R/yDFGaRfiVhUtm1iVTklxFti4hJQdit35eaYd8l7j+waG7I1KBGvxNPDkGaZxyQp/IxXyd78zs8dKzQbGwJSIOsEIh38T9hINc/3MBWFnxOL7qR9pj98/T4couXYrv+qr8rU7zBs983TrxoWnXfneIewvhcM22CpWTrHnjLgH0OdsiCncSStX9kd5Tj2G6ksJEeS4O8zfZhkKOZ5klfwUjwecxCKZo95TGPo+OkhhBorDgDe2ltPAm/RYVE9YvEupHUhtduMO5UWbQWF77PQQL8X0+6QWkohxZwc4XivKCxkwd0TIRF30LAbXv+H4laoL8QboNJ8uDD8ZCvut8uwrUfjDy8KNBIz2pOlMLBZ2DAgCXNMm3WHoWfD/VDVX7ANBIBY4ikJm7JWpKecZFpsUWTk/I4lNhWCku/vaB14SeaNikrUPeXkgVNeJSf8okdu5TyaAbqUdSb23vz+nHwOsNNpOl8kr/WoKqU6Ukadh4EUZsevTDveFq6M2BShx4sbPYD2HLSGCQLiYyRm4EWbdV7TzsoqyjNV7G3RB/gv87vfx0Xi8TlbYLqYKrQwPAa8hbX2iB/W55Fwt46Iq3RZ3ntqBJlGAZu+CdSRobjHmW4Lc=
    username: AgBurJ8BHdwkpIW6MpjWyiipPj2hDO3uwHrggNRXgANmQ8MPT3AS28Wv61RAic4diic6KyNwJ+XP0e7WRBtOFKl0OjyFgnzgBIJvTNAvJjbzYkTBe/W7TgJRSsLWdluayL9fzxylr9k2ubJQgLDGPXPVn/elVa7n+zXhBgL0SfFSj2FoXkK0O6ZLEKjfqgLyjpRKYXfQII3si6WYRatSA11sU37vkZ71IohPWfQPHVVf6m0sgSbnOd1m6Ukum73BUhwE0KfGsHkR9h+LHSIdb7lZ+o+y7d2X3+Yl8yBVmjVa+64FeOIFZz9xC0yEOX0d/7oqNCV6Lx4KzITf9CdV8Zr2Qm4HMlmFesMkjK6AsXDfq1Hqt6+TCjLIi6Iz5GxgootQR8La7kLzhfoZJLzLtWAoa+auygwlVvIusuW+R7fOxCIQjqMKovY1SWB88XY5umxsfTN7YUe6xpWK1PbnpyYWo41pf5qOfkOU78IyYY417EzokQnSBGPxKdOcG2SeimEwCJJKFmJsxRavh8meEfiuLEMNytwXRTZ/Ufw/QSZq3ljl3BFJofY69IGSaf9p1Fjm/C8f2pnMSQUfitcuZXy136bG7M1kdzjpVaiprbKq22qZxPO3gqyeF0EWOKmVGtu8iGyk7eVKxpDegOaZZGIkskiCf0IGEmgBLm2S3qgtPnzYVQjdP0xBbO+KJuRKEaU/9I81Bk/1hywydSQ+ecEgBOa/vABdr8VigB4=
  template:
    metadata:
      creationTimestamp: null
      name: openvpn
      namespace: media
status: {}

