---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
      release: transmission
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transmission
        release: transmission
    spec:
      volumes:
        - name: media-downloads
          persistentVolumeClaim:
            claimName: media-downloads-pvc
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data-pvc
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
            type: ''
      containers:
        - name: transmission
          image: 'haugene/transmission-openvpn:latest-armhf'
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          env:
            - name: OPENVPN_PROVIDER
              value: NORDVPN
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openvpnuser
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openvpnuser
                  key: password
            - name: NORDVPN_PROTOCOL
              value: TCP
            - name: NORDVPN_COUNTRY
              value: NL
            - name: NORDVPN_CATEGORY
              value: P2P
            - name: LOCAL_NETWORK
              value: 192.168.0.0/24
            - name: TRANSMISSION_PEER_PORT
              value: '47444'
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: /downloads/transmission
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TRANSMISSION_RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transmissionuser
                  key: password
            - name: TRANSMISSION_RPC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: transmissionuser
                  key: user
            - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
              value: 'true'
            - name: TRANSMISSION_INCOMPLETE_DIR_ENABLED
              value: 'false'
            - name: TRANSMISSION_INCOMPLETE_DIR
              value: /downloads/incomplete
            - name: TRANSMISSION_WATCH_DIR
              value: /downloads/watch
            - name: TRANSMISSION_RATIO_LIMIT
              value: '0'
            - name: TRANSMISSION_RATIO_LIMIT_ENABLED
              value: 'true'
          resources: {}
          volumeMounts:
            - name: media-data
              mountPath: /data
            - name: media-downloads
              mountPath: /downloads/transmission
              subPath: ""
            - name: dev-tun
              mountPath: /dev/net/tun
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: transmission
  name: transmission
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9091
  selector:
    app: transmission
  type: ClusterIP