apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission
  namespace: media
spec:
  encryptedData:
    password: AgA0aC1nNZSSHEDvSvU3x9ENVLkHM1ycM2FDoq9hjB9kGt8VP9zWvjSeaAn7nB62o6dcYhUvDmL949ERZBkeSbgVYM8LJonKYM/oh7BOB/uhNAQebSzZfYbEpz7QuD0QDzz4vFfWfJEU6zPxIgrHdsGBqirsGPlLvkUBK6NUCUjgPZkD1Vv3ZCQ9mXqovvNOpi+l3m5c+UoUuZ9qpPRw0HfaUf0hxbjvL8tBp21QrqdbAgSsIiGC0CypiH4UEhkuVlojIDSGaczika/iLEUaxILJaiPW9EgGHQovKHITjpwYYnXV6zxFDfCsE7Wob3RxjMFMQeR0XTC/y07fe/aEvj27VY/IcDixUiqiiPUdKkr0huNQ2N0S7NQ5V+s9tuwKPW/rsvn7D6OqtCBESKhTjY1EMRkHZS5ve6cnQPD65IHhNTdxC5mlKcZOonQDCATHBG49TLs13akdbNxvvtDHNQvDEI1l95zGX8yP4LzfvfDZf+UHkLd+nhWTse9m9ty9+27H9MBdcftLOdUz8wDNRdKKlAuI730HlXEVcHAJ8OwiKPeA1UT89Tqt79FOIhblMac6Uvx76chAyZnHsAR9nfnOn2tagp9Oi/mny+0qRQHqsQAVLfmD2/LM4W+5HRFL/p47oNZvcKoFY2r/9gvHiKTrVmJW6m7+oc95k+Rg3cB0qXkVs+rzU+lzUukpB6Ie3Ja8rzG3d6VSxxlAD1EGxRXjcpa9umtfceXRv/IBBwrFCi4ByL/bbwkFedZOdqwtcDrVYTsMYOBFiCBmqXLyd2rZ2Q==
    username: AgCl6TZDSRQ51t5Vljj5HExxBGiPLfnbsVVtLFbvXAik254cAnlTCaCnmvdYBiy9WbGEgS6TZLh7y4cCXuiU32luxTW+t8zxAiSBOW8WmiB0kxjtUWOjwXSTO/WVtNh+Gty5B8PrEFI2G9NFSLI3IeZ5ktdNTh7lEzbHoeTLFsFp2vochkYjtSzHGz+c8ewOVb0ExEaO4BLHnpOTQqh2L30NyVRc7pOIbJKwJKxiYl2ChA8smwPwrqFsamtm1CMJF7qPxnjJVycwyH4F618oeiweZAb2QZyNsTfCQ5XFn2rWPSrVLLuZmRoK9NuGAi6/o786FcjuspgXNjiGDiGjqwPaASRavFPUUAN/IaTgo0ecdyVA1EQNwYVGWGU1GiWLEx+Tv+Actem8tBrU3uyQ2hCfoUEKMn56B/p4I0hrV/tU9MP/DSbpXTssNT8BFoXgnxye1a+TMHaKu0GQrFF76ZGgYzMIt5pxghoDqeYCWPSBXzeN6k5eKYEiXl67C8ROmnr0uziIivwuV7zzd8GLQ/ph+wRd2TgmRVURIVZFWB/2HjYY9DzPvtv/is5ZsnhPKvOdp8rCMG2mD4+hatrC+eeJidL0heL4I5kS7HjTljmiJDmfoDlHt7s7b3V4wieXPp833KgTWOlBB+YwVUs91+wuLgqJPzV354V3DhRuv9HxsepAy4zULON3nCgXNQfykp2yqos8b5NaMMai2Ck=
  template:
    metadata:
      creationTimestamp: null
      name: transmission
      namespace: media

