---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-automation-config-pv
  namespace: home-automation
spec:
  storageClassName: data
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-automation-config-pvc
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 5Gi