apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openvpn
  namespace: media
spec:
  encryptedData:
    password: AgCnwnldmVJefmczmuHS9oqpttelAn/9HRZvmhYgcu4O8HmZZgetweLoWHxwDmppl68CKdOfcfUWxalPmJVwoKLonBskFoGaQDCdIJpV4GXCvUrRZS0XSGofLr+MPmqICx8We9IDOnCiTg205zc5vg5az6k5KOLeA2IhZ4d87YMuxarIPj97RE2t+h+SCSetm7nxMD46M0aC5QatVskGq3oeni0e0ASQwxO2jmVZ59B7WgRZ6xMSiPye1bFfOnp3hdscLxOXK9Q8sjKcVAfXeyfj1ei1BkfnE9yPZxMdEa6FN8d6GtoMcv8xKVIISRhK3K/87GOkJqTYHYxzgK6JYCiskGzJWfNHsidU00YcT7DOpRcoPQSWWt4YcrX5u85StEgc3LdCSOElpsJSQryBjEwHSXzJOaZS+oOhi6+P0WX3Kh9uSP/CD6F/1WFq2JgS+Njo3VOetOZMzF+7SDSH9dZjOB3EWCTuxjRN0OFfGn5enviztAZFk9iMvknj3/zyQ2oqLkOR6vVlLQI9RMLu2hxp+MlIJmEwXSLqWyMzC8fJZib7fITqzDxMw/s5cSh1SFPJsFMK8iuIUGAY4fY0qUYsoxh1u0HK5tvAIsDOpegpN6ZxPAZWDAd6SZZmupu4L5Yepmqp5198qEhvNHFMFYSasEo6dwNmE1EitF+i47MPrzM4KQ/xB3nd9ns+dytUlZvgFppV5v11CrUgRVN+Qo2rbRoC+jdE46hqw4+mruHdsVC2CB9ykp1dOuSYscMWF40=
    username: AgCKKx+1rAtOeY4lDHW4Ik2EfL0OImOYANJAr60tsgoN0RJ2MQLUWybxP9q4yAB4+EpFOj8UsKVJcfN8D20SD7XWFsqqzc6YGIdldRkbiJWcXkgQvhA+w1KwtE1n+QCRnd0KdoHTNbpuLte6W1UOeCHyXKXL3/rouumNuOqU6k9Fj9qlC6JHq19IDxcPIKNXhrgeGW6EsuiwI3H4DapTcca8YrIyZZGeS9cRiVVD7C12HOj7a0il0x5QbF41NsGngNv7qXolc41aI1G3p38jNaJYZd3zHF9mKxyKjqpVlfWJWsYOGZKUyomZsXBt048m6ia2tMieb1397z6Q12GWDRTK8SDl6/euTzTw4hlCFoWNioRUoNKj64gQ1f1tI99DfrS7jyNhi5kqdtmgaD1okHblvkd8fePd1Gsg+CgLuBZx+znTfyXgdrT9M3Gg3iFXUJayDLSq8XvtQ8P/PJhp7axqBSNWq/dx0t46Dd+cQPtaVgjD2VxGBp7wwcPktslfuMPyJ1rhCgMhIEVs1H4pE+jGuvBd5zxnhBMX/iN/T5YRbwLYP9wK5oTzQZ9zZVD8NokdO5WxXlGy2S1ak3MLDjeqTv9bpVhfNj05lZ8RR66kq2OBG2ze0j2HDsDipJZ3Gk/ZDOqSEKA1ggahbr6pzGRYQl0QUBXfThrbxymskOg9LK9OzEVb0KMkd/yL7mahqkfVOh4Gi2AHEe2TKARUkyDkxAleKt+e4/SQbYw=
  template:
    metadata:
      creationTimestamp: null
      name: openvpn
      namespace: media

