---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
  namespace: media
spec:
  storageClassName: data
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/nfsshare/Kubernetes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 500Mi