---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-jellyfin-pv
  namespace: media
spec:
  storageClassName: data
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/jellyfin"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-jellyfin-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 50Gi