---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-videos-pv
  namespace: media
spec:
  storageClassName: data
  capacity:
    storage: 2900Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/videos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-videos-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 2900Gi