---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
spec:
  storageClassName: data
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #
  # @CHANGEME - Update server and path to your NFS server
  #
  nfs:
    server: 192.168.1.202
    path: "/Shared Videos"
  mountOptions:
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=32768
    - wsize=32768
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-videos-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 3Gi