---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: docker.io/linuxserver/radarr
        imagePullPolicy: IfNotPresent
        name: radarr
        ports:
        - containerPort: 7878
          protocol: TCP
        volumeMounts:
          - name: media-data
            mountPath: "/config"
            subPath: "radarr"
          - name: media-downloads
            mountPath: "/downloads/transmission"
            subPath: ""
          - name: media-videos
            mountPath: "/movies"
            subPath: ""
      restartPolicy: Always
      volumes:
      - name: media-downloads
        persistentVolumeClaim:
          claimName: media-downloads-pvc
      - name: media-videos
        persistentVolumeClaim:
          claimName: media-videos-pvc
      - name: media-data
        persistentVolumeClaim:
          claimName: media-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: media
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7878
  selector:
    app: radarr
  type: ClusterIP