---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      nodeName: k8s-worker-01
      containers:
      - env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '100'
        image: docker.io/linuxserver/radarr
        imagePullPolicy: IfNotPresent
        name: radarr
        ports:
        - containerPort: 7878
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 150Mi
        volumeMounts:
          - name: media-config
            mountPath: "/config"
            subPath: "radarr"
          - name: media-downloads
            mountPath: "/downloads"
          - name: media-videos
            mountPath: "/movies"
      restartPolicy: Always
      volumes:
      - name: media-downloads
        persistentVolumeClaim:
          claimName: media-downloads-pvc
      - name: media-videos
        persistentVolumeClaim:
          claimName: media-videos-pvc
      - name: media-config
        persistentVolumeClaim:
          claimName: media-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: media
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7878
  selector:
    app: radarr
  type: ClusterIP