---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: docker.io/homeassistant/raspberrypi4-homeassistant
        imagePullPolicy: IfNotPresent
        name: home-assistant
        ports:
        - containerPort: 8123
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          subPath: "home-assistant"
          name: configurations
      restartPolicy: Always
      volumes:
      - name: configurations
        persistentVolumeClaim:
          claimName: automation-configurations
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
  name: home-assistant
  namespace: home-automation
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8123
  selector:
    app: home-assistant
  type: LoadBalancer